version: '3.9'

services:
  strogino:
    hostname: strogino
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../zoo:/root/zoo
      - ../../mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "222:22"
    deploy:
      replicas: 1
