version: '3.9'

services:
  strogino:
    image: strogino:ssh
    hostname: strogino
    volumes:
      - ../../zoo:/root/zoo
      - ../../mysql:/var/lib/mysql
      - ~/git-credentials:/root/.git-credentials
    ports:
      - "3306:3306"
      - "222:22"
    deploy:
      replicas: 1
