version: '3.8'

services:
  ubuntu-2204:
    image: ubuntu:22.04
    volumes:
      - ./zoo:/root/zoo
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "222:22"
    deploy:
      replicas: 1
